// <auto-generated />
using System;
using FarmOu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmOu.Data.Migrations
{
    [DbContext(typeof(FarmOuDbContext))]
    [Migration("20250430080107_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmOu.Data.Models.Crop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HarvestingTimeInMiliSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("OverallBought")
                        .HasColumnType("int");

                    b.Property<int>("OverallSold")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPerHarvest")
                        .HasColumnType("int");

                    b.Property<float>("XpPerHarvest")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Crops");

                    b.HasData(
                        new
                        {
                            Id = "a3f1e7c2-4b5d-4e12-9f07-1b2c3d4e5f60",
                            HarvestingTimeInMiliSeconds = 2500,
                            Name = "Wheat",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 4,
                            XpPerHarvest = 8f
                        },
                        new
                        {
                            Id = "b4e2f8d3-5c6e-4f23-8a18-2c3d4e5f6a70",
                            HarvestingTimeInMiliSeconds = 3000,
                            Name = "Bell Pepper",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 2,
                            XpPerHarvest = 5f
                        },
                        new
                        {
                            Id = "c5f309e4-6d7f-4g34-1b29-3d4e5f6a7b80",
                            HarvestingTimeInMiliSeconds = 3500,
                            Name = "Carrot",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 3,
                            XpPerHarvest = 9f
                        },
                        new
                        {
                            Id = "d6g410f5-7e80-4h45-2c30-4e5f6a7b8c90",
                            HarvestingTimeInMiliSeconds = 4000,
                            Name = "Mushroom",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 1,
                            XpPerHarvest = 30f
                        },
                        new
                        {
                            Id = "e7h521g6-8f91-4i56-3d41-5f6a7b8c9d01",
                            HarvestingTimeInMiliSeconds = 4500,
                            Name = "Potato",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 2,
                            XpPerHarvest = 10f
                        },
                        new
                        {
                            Id = "f8i632h7-9g02-4j67-4e52-6a7b8c9d0e12",
                            HarvestingTimeInMiliSeconds = 6000,
                            Name = "Corn",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 3,
                            XpPerHarvest = 12f
                        },
                        new
                        {
                            Id = "g9j743i8-0h13-4k78-5f63-7b8c9d0e1f23",
                            HarvestingTimeInMiliSeconds = 7000,
                            Name = "Tomato",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 2,
                            XpPerHarvest = 15f
                        },
                        new
                        {
                            Id = "h0k854j9-1i24-4l89-6g74-8c9d0e1f2g34",
                            HarvestingTimeInMiliSeconds = 9000,
                            Name = "Rice",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 3,
                            XpPerHarvest = 16f
                        },
                        new
                        {
                            Id = "i1l965k0-2j35-4m90-7h85-9d0e1f2g3h45",
                            HarvestingTimeInMiliSeconds = 10000,
                            Name = "Strawberry",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 2,
                            XpPerHarvest = 18f
                        },
                        new
                        {
                            Id = "j2m076l1-3k46-4n01-8i96-0e1f2g3h4i56",
                            HarvestingTimeInMiliSeconds = 12000,
                            Name = "Cotton",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 2,
                            XpPerHarvest = 20f
                        },
                        new
                        {
                            Id = "k3n187m2-4l57-4o12-9j07-1f2g3h4i5j67",
                            HarvestingTimeInMiliSeconds = 12500,
                            Name = "Dragonfruit",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 2,
                            XpPerHarvest = 28f
                        },
                        new
                        {
                            Id = "l4o298n3-5m68-4p23-0k18-2g3h4i5j6k78",
                            HarvestingTimeInMiliSeconds = 13000,
                            Name = "Blueberry",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 2,
                            XpPerHarvest = 22f
                        },
                        new
                        {
                            Id = "m5p309o4-6n79-4q34-1l29-3h4i5j6k7l89",
                            HarvestingTimeInMiliSeconds = 14000,
                            Name = "Grapes",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 3,
                            XpPerHarvest = 18f
                        },
                        new
                        {
                            Id = "n6q410p5-7o80-4r45-2m30-4i5j6k7l8m90",
                            HarvestingTimeInMiliSeconds = 15000,
                            Name = "Pumpkin",
                            OverallBought = 0,
                            OverallSold = 0,
                            QuantityPerHarvest = 1,
                            XpPerHarvest = 25f
                        });
                });

            modelBuilder.Entity("FarmOu.Data.Models.CropBuying", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CropId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BoughtAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BuyPricePerCrop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FarmerId", "CropId");

                    b.HasIndex("CropId");

                    b.ToTable("CropBuyings");
                });

            modelBuilder.Entity("FarmOu.Data.Models.CropSell", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CropId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellPricePerCrop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SoldAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FarmerId", "CropId");

                    b.HasIndex("CropId");

                    b.ToTable("CropSells");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Farmer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Coins")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentFarmerXp")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("XpLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("XpLevelId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmerCrop", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CropId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FarmerId", "CropId");

                    b.HasIndex("CropId");

                    b.ToTable("FarmersCrops");
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmerTool", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToolId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FarmerId", "ToolId");

                    b.HasIndex("ToolId");

                    b.ToTable("FarmersTools");
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmingSession", b =>
                {
                    b.Property<string>("CropId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToolId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("FarmedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("HarvestedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CropId", "FarmerId", "ToolId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("ToolId");

                    b.ToTable("FarmingsSessions");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Tool", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CropId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GeneralBonusQuantityPerHarvest")
                        .HasColumnType("int");

                    b.Property<int>("GeneralSavingTimeInMiliSeconds")
                        .HasColumnType("int");

                    b.Property<int>("LevelNeeded")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("SpecificBonusQuantityPerHarvest")
                        .HasColumnType("int");

                    b.Property<int>("SpecificSavingTimeInMiliSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            Id = "0794a9c9-f6d4-4c11-a1c0-f77ee2cac235",
                            CropId = "a3f1e7c2-4b5d-4e12-9f07-1b2c3d4e5f60",
                            GeneralBonusQuantityPerHarvest = 0,
                            GeneralSavingTimeInMiliSeconds = 0,
                            LevelNeeded = 5,
                            Name = "Wheatwind Scythe",
                            Rarity = 0,
                            SpecificBonusQuantityPerHarvest = 1,
                            SpecificSavingTimeInMiliSeconds = 500
                        },
                        new
                        {
                            Id = "7e6e5f03-0f1f-43e8-a3d0-9cab05a9a117",
                            CropId = "b4e2f8d3-5c6e-4f23-8a18-2c3d4e5f6a70",
                            GeneralBonusQuantityPerHarvest = 0,
                            GeneralSavingTimeInMiliSeconds = 0,
                            LevelNeeded = 5,
                            Name = "Pepper Pruner",
                            Rarity = 0,
                            SpecificBonusQuantityPerHarvest = 1,
                            SpecificSavingTimeInMiliSeconds = 500
                        },
                        new
                        {
                            Id = "b63467bf-8dc6-472a-88f1-af869eefac8a",
                            CropId = "c5f309e4-6d7f-4g34-1b29-3d4e5f6a7b80",
                            GeneralBonusQuantityPerHarvest = 0,
                            GeneralSavingTimeInMiliSeconds = 0,
                            LevelNeeded = 5,
                            Name = "Carrot Crescendo",
                            Rarity = 0,
                            SpecificBonusQuantityPerHarvest = 1,
                            SpecificSavingTimeInMiliSeconds = 500
                        },
                        new
                        {
                            Id = "7d6cbabc-cbfb-42eb-bd93-590ed5f6f3da",
                            CropId = "d6g410f5-7e80-4h45-2c30-4e5f6a7b8c90",
                            GeneralBonusQuantityPerHarvest = 0,
                            GeneralSavingTimeInMiliSeconds = 0,
                            LevelNeeded = 5,
                            Name = "Fungus Forger",
                            Rarity = 0,
                            SpecificBonusQuantityPerHarvest = 1,
                            SpecificSavingTimeInMiliSeconds = 500
                        },
                        new
                        {
                            Id = "a4ccf8be-ec77-434c-b454-1d250716547c",
                            CropId = "e7h521g6-8f91-4i56-3d41-5f6a7b8c9d01",
                            GeneralBonusQuantityPerHarvest = 0,
                            GeneralSavingTimeInMiliSeconds = 0,
                            LevelNeeded = 5,
                            Name = "Tater Tamer",
                            Rarity = 0,
                            SpecificBonusQuantityPerHarvest = 1,
                            SpecificSavingTimeInMiliSeconds = 500
                        },
                        new
                        {
                            Id = "27f51def-481c-4cf1-b7e9-07aadfe73d60",
                            CropId = "f8i632h7-9g02-4j67-4e52-6a7b8c9d0e12",
                            GeneralBonusQuantityPerHarvest = 0,
                            GeneralSavingTimeInMiliSeconds = 0,
                            LevelNeeded = 15,
                            Name = "Corncob Clarifier",
                            Rarity = 1,
                            SpecificBonusQuantityPerHarvest = 1,
                            SpecificSavingTimeInMiliSeconds = 1000
                        },
                        new
                        {
                            Id = "a2cc6a9a-26a4-4dcf-a2ae-f9527b126fcd",
                            CropId = "g9j743i8-0h13-4k78-5f63-7b8c9d0e1f23",
                            GeneralBonusQuantityPerHarvest = 0,
                            GeneralSavingTimeInMiliSeconds = 0,
                            LevelNeeded = 15,
                            Name = "Tomato Twister",
                            Rarity = 1,
                            SpecificBonusQuantityPerHarvest = 1,
                            SpecificSavingTimeInMiliSeconds = 1000
                        },
                        new
                        {
                            Id = "a4f46365-6d04-4780-969e-6ead81d7faca",
                            CropId = "h0k854j9-1i24-4l89-6g74-8c9d0e1f2g34",
                            GeneralBonusQuantityPerHarvest = 0,
                            GeneralSavingTimeInMiliSeconds = 0,
                            LevelNeeded = 15,
                            Name = "Rice Reaper",
                            Rarity = 1,
                            SpecificBonusQuantityPerHarvest = 1,
                            SpecificSavingTimeInMiliSeconds = 1000
                        },
                        new
                        {
                            Id = "dcad4c4b-3f28-4e25-b5dd-6a224eb684b3",
                            CropId = "i1l965k0-2j35-4m90-7h85-9d0e1f2g3h45",
                            GeneralBonusQuantityPerHarvest = 0,
                            GeneralSavingTimeInMiliSeconds = 0,
                            LevelNeeded = 15,
                            Name = "Berry Brawler",
                            Rarity = 1,
                            SpecificBonusQuantityPerHarvest = 1,
                            SpecificSavingTimeInMiliSeconds = 1000
                        },
                        new
                        {
                            Id = "16559923-bf70-4f24-846d-4711303ec9b4",
                            CropId = "j2m076l1-3k46-4n01-8i96-0e1f2g3h4i56",
                            GeneralBonusQuantityPerHarvest = 0,
                            GeneralSavingTimeInMiliSeconds = 0,
                            LevelNeeded = 15,
                            Name = "Cotton Cutter",
                            Rarity = 1,
                            SpecificBonusQuantityPerHarvest = 1,
                            SpecificSavingTimeInMiliSeconds = 1000
                        },
                        new
                        {
                            Id = "1e6c2c50-1e05-4a5a-b990-32813b97823c",
                            CropId = "l4o298n3-5m68-4p23-0k18-2g3h4i5j6k78",
                            GeneralBonusQuantityPerHarvest = 1,
                            GeneralSavingTimeInMiliSeconds = 1000,
                            LevelNeeded = 25,
                            Name = "Blueberry Blitz",
                            Rarity = 2,
                            SpecificBonusQuantityPerHarvest = 2,
                            SpecificSavingTimeInMiliSeconds = 1500
                        },
                        new
                        {
                            Id = "950d94f9-8487-4380-b3c7-fc533e8d8c89",
                            CropId = "n6q410p5-7o80-4r45-2m30-4i5j6k7l8m90",
                            GeneralBonusQuantityPerHarvest = 1,
                            GeneralSavingTimeInMiliSeconds = 1000,
                            LevelNeeded = 25,
                            Name = "Pumpkin Pulverizer",
                            Rarity = 2,
                            SpecificBonusQuantityPerHarvest = 2,
                            SpecificSavingTimeInMiliSeconds = 1500
                        },
                        new
                        {
                            Id = "3566e129-a898-4f81-b1af-1ba89bb1c901",
                            CropId = "k3n187m2-4l57-4o12-9j07-1f2g3h4i5j67",
                            GeneralBonusQuantityPerHarvest = 1,
                            GeneralSavingTimeInMiliSeconds = 1000,
                            LevelNeeded = 25,
                            Name = "Dragonfruit Dicer",
                            Rarity = 2,
                            SpecificBonusQuantityPerHarvest = 2,
                            SpecificSavingTimeInMiliSeconds = 1500
                        },
                        new
                        {
                            Id = "ac633fba-5c14-4a42-b616-0bd729e5841a",
                            CropId = "m5p309o4-6n79-4q34-1l29-3h4i5j6k7l89",
                            GeneralBonusQuantityPerHarvest = 1,
                            GeneralSavingTimeInMiliSeconds = 1000,
                            LevelNeeded = 25,
                            Name = "Grape Grappler",
                            Rarity = 2,
                            SpecificBonusQuantityPerHarvest = 2,
                            SpecificSavingTimeInMiliSeconds = 1500
                        },
                        new
                        {
                            Id = "ad5f3d9f-86cb-4e96-b959-6ef30528e5e1",
                            CropId = "a3f1e7c2-4b5d-4e12-9f07-1b2c3d4e5f60",
                            GeneralBonusQuantityPerHarvest = 2,
                            GeneralSavingTimeInMiliSeconds = 1500,
                            LevelNeeded = 35,
                            Name = "Mythic Wheatwind Scythe",
                            Rarity = 4,
                            SpecificBonusQuantityPerHarvest = 3,
                            SpecificSavingTimeInMiliSeconds = 2000
                        },
                        new
                        {
                            Id = "76a6c530-ac39-4029-85c2-e67caccdb192",
                            CropId = "f8i632h7-9g02-4j67-4e52-6a7b8c9d0e12",
                            GeneralBonusQuantityPerHarvest = 2,
                            GeneralSavingTimeInMiliSeconds = 1500,
                            LevelNeeded = 35,
                            Name = "Mythic Corncob Clarifier",
                            Rarity = 4,
                            SpecificBonusQuantityPerHarvest = 3,
                            SpecificSavingTimeInMiliSeconds = 2000
                        },
                        new
                        {
                            Id = "bcba2bf4-969f-4f7d-813c-4810a5f377b7",
                            CropId = "i1l965k0-2j35-4m90-7h85-9d0e1f2g3h45",
                            GeneralBonusQuantityPerHarvest = 2,
                            GeneralSavingTimeInMiliSeconds = 1500,
                            LevelNeeded = 35,
                            Name = "Mythic Berry Brawler",
                            Rarity = 4,
                            SpecificBonusQuantityPerHarvest = 3,
                            SpecificSavingTimeInMiliSeconds = 2000
                        },
                        new
                        {
                            Id = "8ccd5537-ccd7-4007-88c6-8a1be39127b2",
                            CropId = "j2m076l1-3k46-4n01-8i96-0e1f2g3h4i56",
                            GeneralBonusQuantityPerHarvest = 2,
                            GeneralSavingTimeInMiliSeconds = 1500,
                            LevelNeeded = 35,
                            Name = "Mythic Cotton Cutter",
                            Rarity = 4,
                            SpecificBonusQuantityPerHarvest = 3,
                            SpecificSavingTimeInMiliSeconds = 2000
                        },
                        new
                        {
                            Id = "34a2d676-241b-43e8-a3dd-67c425570920",
                            CropId = "m5p309o4-6n79-4q34-1l29-3h4i5j6k7l89",
                            GeneralBonusQuantityPerHarvest = 2,
                            GeneralSavingTimeInMiliSeconds = 1500,
                            LevelNeeded = 35,
                            Name = "Mythic Grape Grappler",
                            Rarity = 4,
                            SpecificBonusQuantityPerHarvest = 3,
                            SpecificSavingTimeInMiliSeconds = 2000
                        },
                        new
                        {
                            Id = "7f22cd92-14b2-4122-8444-d6e4d5ececde",
                            CropId = "b4e2f8d3-5c6e-4f23-8a18-2c3d4e5f6a70",
                            GeneralBonusQuantityPerHarvest = 3,
                            GeneralSavingTimeInMiliSeconds = 2000,
                            LevelNeeded = 50,
                            Name = "Godlike Pepper Pruner",
                            Rarity = 5,
                            SpecificBonusQuantityPerHarvest = 4,
                            SpecificSavingTimeInMiliSeconds = 2500
                        },
                        new
                        {
                            Id = "d3adc72a-1d09-454c-a45b-5b3f80f41987",
                            CropId = "e7h521g6-8f91-4i56-3d41-5f6a7b8c9d01",
                            GeneralBonusQuantityPerHarvest = 3,
                            GeneralSavingTimeInMiliSeconds = 2000,
                            LevelNeeded = 50,
                            Name = "Godlike Tater Tamer",
                            Rarity = 5,
                            SpecificBonusQuantityPerHarvest = 4,
                            SpecificSavingTimeInMiliSeconds = 2500
                        },
                        new
                        {
                            Id = "3307ec62-9b30-4134-9b99-742d49803994",
                            CropId = "l4o298n3-5m68-4p23-0k18-2g3h4i5j6k78",
                            GeneralBonusQuantityPerHarvest = 3,
                            GeneralSavingTimeInMiliSeconds = 2000,
                            LevelNeeded = 50,
                            Name = "Godlike Blueberry Blitz",
                            Rarity = 5,
                            SpecificBonusQuantityPerHarvest = 4,
                            SpecificSavingTimeInMiliSeconds = 2500
                        },
                        new
                        {
                            Id = "9431273a-2df2-466b-94f0-da13e7735b66",
                            CropId = "n6q410p5-7o80-4r45-2m30-4i5j6k7l8m90",
                            GeneralBonusQuantityPerHarvest = 3,
                            GeneralSavingTimeInMiliSeconds = 2000,
                            LevelNeeded = 50,
                            Name = "Godlike Pumpkin Pulverizer",
                            Rarity = 5,
                            SpecificBonusQuantityPerHarvest = 4,
                            SpecificSavingTimeInMiliSeconds = 2500
                        });
                });

            modelBuilder.Entity("FarmOu.Data.Models.ToolBuying", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToolId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BoughtAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FarmerId", "ToolId");

                    b.HasIndex("ToolId");

                    b.ToTable("ToolsBuyings");
                });

            modelBuilder.Entity("FarmOu.Data.Models.XpLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("NeededFarmerXp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("XpLevels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 1,
                            NeededFarmerXp = 100
                        },
                        new
                        {
                            Id = 2,
                            Level = 2,
                            NeededFarmerXp = 120
                        },
                        new
                        {
                            Id = 3,
                            Level = 3,
                            NeededFarmerXp = 140
                        },
                        new
                        {
                            Id = 4,
                            Level = 4,
                            NeededFarmerXp = 160
                        },
                        new
                        {
                            Id = 5,
                            Level = 5,
                            NeededFarmerXp = 180
                        },
                        new
                        {
                            Id = 6,
                            Level = 6,
                            NeededFarmerXp = 200
                        },
                        new
                        {
                            Id = 7,
                            Level = 7,
                            NeededFarmerXp = 220
                        },
                        new
                        {
                            Id = 8,
                            Level = 8,
                            NeededFarmerXp = 240
                        },
                        new
                        {
                            Id = 9,
                            Level = 9,
                            NeededFarmerXp = 260
                        },
                        new
                        {
                            Id = 10,
                            Level = 10,
                            NeededFarmerXp = 280
                        },
                        new
                        {
                            Id = 11,
                            Level = 11,
                            NeededFarmerXp = 300
                        },
                        new
                        {
                            Id = 12,
                            Level = 12,
                            NeededFarmerXp = 320
                        },
                        new
                        {
                            Id = 13,
                            Level = 13,
                            NeededFarmerXp = 340
                        },
                        new
                        {
                            Id = 14,
                            Level = 14,
                            NeededFarmerXp = 360
                        },
                        new
                        {
                            Id = 15,
                            Level = 15,
                            NeededFarmerXp = 380
                        },
                        new
                        {
                            Id = 16,
                            Level = 16,
                            NeededFarmerXp = 400
                        },
                        new
                        {
                            Id = 17,
                            Level = 17,
                            NeededFarmerXp = 420
                        },
                        new
                        {
                            Id = 18,
                            Level = 18,
                            NeededFarmerXp = 440
                        },
                        new
                        {
                            Id = 19,
                            Level = 19,
                            NeededFarmerXp = 460
                        },
                        new
                        {
                            Id = 20,
                            Level = 20,
                            NeededFarmerXp = 480
                        },
                        new
                        {
                            Id = 21,
                            Level = 21,
                            NeededFarmerXp = 500
                        },
                        new
                        {
                            Id = 22,
                            Level = 22,
                            NeededFarmerXp = 520
                        },
                        new
                        {
                            Id = 23,
                            Level = 23,
                            NeededFarmerXp = 540
                        },
                        new
                        {
                            Id = 24,
                            Level = 24,
                            NeededFarmerXp = 560
                        },
                        new
                        {
                            Id = 25,
                            Level = 25,
                            NeededFarmerXp = 580
                        },
                        new
                        {
                            Id = 26,
                            Level = 26,
                            NeededFarmerXp = 600
                        },
                        new
                        {
                            Id = 27,
                            Level = 27,
                            NeededFarmerXp = 620
                        },
                        new
                        {
                            Id = 28,
                            Level = 28,
                            NeededFarmerXp = 640
                        },
                        new
                        {
                            Id = 29,
                            Level = 29,
                            NeededFarmerXp = 660
                        },
                        new
                        {
                            Id = 30,
                            Level = 30,
                            NeededFarmerXp = 680
                        },
                        new
                        {
                            Id = 31,
                            Level = 31,
                            NeededFarmerXp = 700
                        },
                        new
                        {
                            Id = 32,
                            Level = 32,
                            NeededFarmerXp = 720
                        },
                        new
                        {
                            Id = 33,
                            Level = 33,
                            NeededFarmerXp = 740
                        },
                        new
                        {
                            Id = 34,
                            Level = 34,
                            NeededFarmerXp = 760
                        },
                        new
                        {
                            Id = 35,
                            Level = 35,
                            NeededFarmerXp = 780
                        },
                        new
                        {
                            Id = 36,
                            Level = 36,
                            NeededFarmerXp = 800
                        },
                        new
                        {
                            Id = 37,
                            Level = 37,
                            NeededFarmerXp = 820
                        },
                        new
                        {
                            Id = 38,
                            Level = 38,
                            NeededFarmerXp = 840
                        },
                        new
                        {
                            Id = 39,
                            Level = 39,
                            NeededFarmerXp = 860
                        },
                        new
                        {
                            Id = 40,
                            Level = 40,
                            NeededFarmerXp = 880
                        },
                        new
                        {
                            Id = 41,
                            Level = 41,
                            NeededFarmerXp = 900
                        },
                        new
                        {
                            Id = 42,
                            Level = 42,
                            NeededFarmerXp = 920
                        },
                        new
                        {
                            Id = 43,
                            Level = 43,
                            NeededFarmerXp = 940
                        },
                        new
                        {
                            Id = 44,
                            Level = 44,
                            NeededFarmerXp = 960
                        },
                        new
                        {
                            Id = 45,
                            Level = 45,
                            NeededFarmerXp = 980
                        },
                        new
                        {
                            Id = 46,
                            Level = 46,
                            NeededFarmerXp = 1000
                        },
                        new
                        {
                            Id = 47,
                            Level = 47,
                            NeededFarmerXp = 1020
                        },
                        new
                        {
                            Id = 48,
                            Level = 48,
                            NeededFarmerXp = 1040
                        },
                        new
                        {
                            Id = 49,
                            Level = 49,
                            NeededFarmerXp = 1060
                        },
                        new
                        {
                            Id = 50,
                            Level = 50,
                            NeededFarmerXp = 1080
                        },
                        new
                        {
                            Id = 51,
                            Level = 51,
                            NeededFarmerXp = 1100
                        },
                        new
                        {
                            Id = 52,
                            Level = 52,
                            NeededFarmerXp = 1120
                        },
                        new
                        {
                            Id = 53,
                            Level = 53,
                            NeededFarmerXp = 1140
                        },
                        new
                        {
                            Id = 54,
                            Level = 54,
                            NeededFarmerXp = 1160
                        },
                        new
                        {
                            Id = 55,
                            Level = 55,
                            NeededFarmerXp = 1180
                        },
                        new
                        {
                            Id = 56,
                            Level = 56,
                            NeededFarmerXp = 1200
                        },
                        new
                        {
                            Id = 57,
                            Level = 57,
                            NeededFarmerXp = 1220
                        },
                        new
                        {
                            Id = 58,
                            Level = 58,
                            NeededFarmerXp = 1240
                        },
                        new
                        {
                            Id = 59,
                            Level = 59,
                            NeededFarmerXp = 1260
                        },
                        new
                        {
                            Id = 60,
                            Level = 60,
                            NeededFarmerXp = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FarmOu.Data.Models.CropBuying", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Crop", "Crop")
                        .WithMany("CropBuyings")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("CropBuyings")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("FarmOu.Data.Models.CropSell", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Crop", "Crop")
                        .WithMany("CropSells")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("CropSells")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Farmer", b =>
                {
                    b.HasOne("FarmOu.Data.Models.XpLevel", "XpLevel")
                        .WithMany("Farmers")
                        .HasForeignKey("XpLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("XpLevel");
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmerCrop", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Crop", "Crop")
                        .WithMany("FarmerCrops")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("FarmerCrops")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmerTool", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("FarmerTools")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Tool", "Tool")
                        .WithMany("FarmerTools")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmingSession", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Crop", "Crop")
                        .WithMany("FarmingSessions")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("FarmingSessions")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Tool", "Tool")
                        .WithMany("FarmingSessions")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Farmer");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Tool", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Crop", "Crop")
                        .WithMany("Tools")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("FarmOu.Data.Models.ToolBuying", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("ToolBuyings")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Tool", "Tool")
                        .WithMany("ToolBuyings")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmOu.Data.Models.Crop", b =>
                {
                    b.Navigation("CropBuyings");

                    b.Navigation("CropSells");

                    b.Navigation("FarmerCrops");

                    b.Navigation("FarmingSessions");

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Farmer", b =>
                {
                    b.Navigation("CropBuyings");

                    b.Navigation("CropSells");

                    b.Navigation("FarmerCrops");

                    b.Navigation("FarmerTools");

                    b.Navigation("FarmingSessions");

                    b.Navigation("ToolBuyings");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Tool", b =>
                {
                    b.Navigation("FarmerTools");

                    b.Navigation("FarmingSessions");

                    b.Navigation("ToolBuyings");
                });

            modelBuilder.Entity("FarmOu.Data.Models.XpLevel", b =>
                {
                    b.Navigation("Farmers");
                });
#pragma warning restore 612, 618
        }
    }
}
