// <auto-generated />
using System;
using FarmOu.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmOu.Data.Migrations
{
    [DbContext(typeof(FarmOuDbContext))]
    partial class FarmOuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmOu.Data.Models.Crop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HarvestingTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("OverallBought")
                        .HasColumnType("int");

                    b.Property<int>("OverallSold")
                        .HasColumnType("int");

                    b.Property<int>("QuantityPerHarvest")
                        .HasColumnType("int");

                    b.Property<float>("XpPerHarvest")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("FarmOu.Data.Models.CropBuying", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CropId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BoughtAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BuyPricePerCrop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FarmerId", "CropId");

                    b.HasIndex("CropId");

                    b.ToTable("CropBuyings");
                });

            modelBuilder.Entity("FarmOu.Data.Models.CropSell", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CropId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellPricePerCrop")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SoldAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FarmerId", "CropId");

                    b.HasIndex("CropId");

                    b.ToTable("CropSells");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Farmer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Coins")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("XpLevelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("XpLevelId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmerCrop", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CropId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("FarmerId", "CropId");

                    b.HasIndex("CropId");

                    b.ToTable("FarmersCrops");
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmerTool", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToolId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FarmerId", "ToolId");

                    b.HasIndex("ToolId");

                    b.ToTable("FarmersTools");
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmingSession", b =>
                {
                    b.Property<string>("CropId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToolId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("FarmedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("HarvestedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CropId", "FarmerId", "ToolId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("ToolId");

                    b.ToTable("FarmingsSessions");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Tool", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CropId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("GeneralBonusQuantityPerHarvest")
                        .HasColumnType("int");

                    b.Property<int>("GeneralSavingTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<int>("LevelNeeded")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<int>("SpecificBonusQuantityPerHarvest")
                        .HasColumnType("int");

                    b.Property<int>("SpecificSavingTimeInSeconds")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("FarmOu.Data.Models.ToolBuying", b =>
                {
                    b.Property<string>("FarmerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ToolId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("BoughtAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FarmerId", "ToolId");

                    b.HasIndex("ToolId");

                    b.ToTable("ToolsBuyings");
                });

            modelBuilder.Entity("FarmOu.Data.Models.XpLevel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CurrentFarmerXp")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("NeededFarmerXp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("XpLevels");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FarmOu.Data.Models.CropBuying", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Crop", "Crop")
                        .WithMany("CropBuyings")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("CropBuyings")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("FarmOu.Data.Models.CropSell", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Crop", "Crop")
                        .WithMany("CropSells")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("CropSells")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Farmer", b =>
                {
                    b.HasOne("FarmOu.Data.Models.XpLevel", "XpLevel")
                        .WithMany("Farmers")
                        .HasForeignKey("XpLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("XpLevel");
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmerCrop", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Crop", "Crop")
                        .WithMany("FarmerCrops")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("FarmerCrops")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmerTool", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("FarmerTools")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Tool", "Tool")
                        .WithMany("FarmerTools")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("FarmOu.Data.Models.FarmingSession", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Crop", "Crop")
                        .WithMany("FarmingSessions")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("FarmingSessions")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Tool", "Tool")
                        .WithMany("FarmingSessions")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Farmer");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Tool", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Crop", "Crop")
                        .WithMany("Tools")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("FarmOu.Data.Models.ToolBuying", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Farmer", "Farmer")
                        .WithMany("ToolBuyings")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Tool", "Tool")
                        .WithMany("ToolBuyings")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmOu.Data.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FarmOu.Data.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FarmOu.Data.Models.Crop", b =>
                {
                    b.Navigation("CropBuyings");

                    b.Navigation("CropSells");

                    b.Navigation("FarmerCrops");

                    b.Navigation("FarmingSessions");

                    b.Navigation("Tools");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Farmer", b =>
                {
                    b.Navigation("CropBuyings");

                    b.Navigation("CropSells");

                    b.Navigation("FarmerCrops");

                    b.Navigation("FarmerTools");

                    b.Navigation("FarmingSessions");

                    b.Navigation("ToolBuyings");
                });

            modelBuilder.Entity("FarmOu.Data.Models.Tool", b =>
                {
                    b.Navigation("FarmerTools");

                    b.Navigation("FarmingSessions");

                    b.Navigation("ToolBuyings");
                });

            modelBuilder.Entity("FarmOu.Data.Models.XpLevel", b =>
                {
                    b.Navigation("Farmers");
                });
#pragma warning restore 612, 618
        }
    }
}
